mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
import views
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('polls.urls', namespace='polls')),
)

polls/urls.py
from django.conf.urls import patterns, include, url

from polls import views

urlpatterns = patterns('',
	#/polls/
	url(r'^$', views.IndexView.as_view(), name='index'),
	#/polls/1
	url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
	#/polls/1/results
	url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
	#/polls/1/vote
	url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
	#/contact/
	url(r'^contact/$', views.contact, name='contact'),
	#ajax vote
	# url(r'^(?P<poll_id>\d+)/ajaxvote/$', views.ajax_vote, name='voteajax'),
)

pollsite/pollsite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pollsite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^polls2/', include('polls2.urls', namespace='polls2')),
    url(r'^admin/', include(admin.site.urls)),
)

polls/models.py
import datetime
from django.utils import timezone
from django.db import models

class Poll(models.Model):
	question = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def __unicode__(self):
		return self.question

	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now

	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'

	def get_number_of_days_past(self):
		delta = str(timezone.now() - self.pub_date).split(':')
		passed = 0
		if delta:
			passed = delta[0].split(',')[0]
		return passed

	def get_absolute_url(self):
		return u"/polls/%s" % self.pk

class Choice(models.Model):
	poll = models.ForeignKey(Poll)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __unicode__(self):
		return self.choice_text

polls/forms.py
from django import forms

class ContactForm(forms.Form):
	subject = forms.CharField(max_length=200)
	message = forms.CharField()
	sender = forms.EmailField()
	cc_myself = forms.BooleanField(required=False)

polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.views import generic
import time
import json

from polls.models import Poll, Choice
from polls.forms import ContactForm

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_polls'

    def get_queryset(self):
        return Poll.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Poll
    template_name = 'polls/detail.html'

    def get_queryset(self, *args, **kwargs):
        return Poll.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'polls/results.html'

def vote(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = poll.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'poll': poll,
            'error_message': 'Please select a valid choice!'
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results', args=(poll.id, )))

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            # process data here
            print form.cleaned_data
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            cc_myself = form.cleaned_data['cc_myself']

            recipients = ['info@example.com']
            if cc_myself:
                recipients.append(sender)

            from django.core.mail import send_mail
            send_mail(subject, message, sender, recipients)
            return HttpResponseRedirect('/')
    else:
        form = ContactForm()

    return render(request, 'polls/contact.html', {
        'form':form
    })

polls/templates/polls/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %} | Pollbin</title>
    <link href="{% static 'polls/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'polls/css/card.css' %}" rel="stylesheet">
    <link href="{% static 'polls/css/fonts.css' %}" rel="stylesheet">
    {% block extra_head %}{% endblock %}
</head>
<body>
{% block body %}
{% block menu %}
{% endblock %}
{% block content %}
{% endblock %}
{% endblock %}
    <script type="text/javascript" src="{% static 'polls/js/jquery-2.1.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'polls/js/randomcardcolor.js' %}"></script>
    <script type="text/javascript" src="{% static 'polls/js/bootstrap.min.js' %}"></script>
</body>
</html>

polls/templates/polls/contact.html
<form action="/contact/" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% load staticfiles %}
{% load app_filters %}
{% block title %}{{poll.question|shortify}}...{% endblock %}
{% block extra_head %}
	<link href="{% static 'polls/css/queform.css' %}" rel="stylesheet">
{% endblock %}
{% block body %}
<div class="container">
	<div class="row clearfix">
		<div class="col-md-4 col-md-offset-4 queform">
			<div class="queform-title">
				<h3>{{poll.question}}</h3>				
			</div>
			<form action=" {% url 'polls:vote' poll.id %} " method="post" role="form"> {% csrf_token %}
				{% for choice in poll.choice_set.all %}
				<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
			    <label for="choice{{ forloop.counter }}">{{choice.choice_text}}</label> 
			    <br>
				{% endfor %}
				<input type="submit" value="VOTE"/>
			    {% if error_message %}<p><strong>{{ error.message }}</strong></p>{% endif %}
			</form>
		</div>
	</div>
</div>
{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block title %}Welcome to Pollbin!{% endblock %}
{% load staticfiles %}
{% block extra_head %}
{% endblock %}

{% block body %}
<div class="container">
{% if latest_polls %}
    <div class="card-container row clearfix">
    {% for poll in latest_polls %}
        <div class="card col-sm-4 col-md-2 column">
        	<h4><a href="{% url 'polls:detail' poll.id %}">{{ poll.question }}</a></h4>            
        </div>
    {% endfor %}
    </div>
{% else %}
    no polls
{% endif %}
	<div class="row clearfix">
		<p><a href="{% url 'polls:contact' %}">Contact me</a></p>		
	</div>
</div>
{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}
{% load staticfiles %}
{% load app_filters %}
{% block title %}{{ poll.question|shortify }}... results{% endblock %}
{% block extra_head %}
	<link href="{% static 'polls/css/queform.css' %}" rel="stylesheet">
{% endblock %}
{% block body %}
<div class="container">
	<div class="row clearfix">
		<div class="col-md-4 col-md-offset-4 queform">			
			<div class="queform-title">
				<h3>{{ poll.question }}</h3>				
			</div>
			<div class="queform-content">
				<ul>
				{% for choice in poll.choice_set.all %}
				    <li>{{ choice.votes }} vote{{ choice.votes|pluralize }} for "{{ choice.choice_text }}"</li>
				{% endfor %}
				</ul>				
			</div>
		</div>
	</div>
</div>
{% endblock %}