mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
import views
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('polls.urls', namespace='polls')),
)

polls/urls.py
from django.conf.urls import patterns, include, url

from polls import views

urlpatterns = patterns('',
	#/polls/
	url(r'^$', views.IndexView.as_view(), name='index'),
	#/polls/1
	url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
	#/polls/1/results
	url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
	#/polls/1/vote
	url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
	#/contact/
	url(r'^contact/$', views.contact, name='contact'),
	#ajax vote
	# url(r'^(?P<poll_id>\d+)/ajaxvote/$', views.ajax_vote, name='voteajax'),
)

pollsite/polls2/urls.py
from django.conf.urls import patterns, url

from polls2 import views

urlpatterns = patterns('',
	# /polls2/
	url(r'^$', views.IndexView.as_view(), name='index'),
	# /polls2/first-question,1
	url(r'^(?P<poll_slug>[-\w]+),(?P<poll_id>\d+)/$', views.DetailView.as_view(), name='detail'),
	# /polls2/first-question,1/vote/
	url(r'^(?P<poll_slug>[-\w]+),(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
	# /polls2/first-question,1/results/
	url(r'^(?P<poll_slug>[-\w]+),(?P<poll_id>\d+)/results/$', views.ResultsView.as_view(), name='results'),
)

pollsite/pollsite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pollsite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^polls2/', include('polls2.urls', namespace='polls2')),
    url(r'^admin/', include(admin.site.urls)),
)

pollsite/polls2/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.template.defaultfilters import slugify

class Poll(models.Model):
    slug = models.SlugField()
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date_published')
    answers = models.IntegerField(default=0)

    def __unicode__(self):
        return self.question

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def get_number_of_answers(self):
        return len(Choice.objects.filter(poll_id=self.id))

    def get_number_of_days_past(self):
        delta = str(timezone.now() - self.pub_date).split(':')
        passed = 0
        if delta:
            passed = delta[0].split(',')[0]
        return passed

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.question)
        super(Poll, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        return ('polls:detail', (self.slug, self.id))

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self. choice_text

class Voter(models.Model):
    ip = models.CharField(max_length=200)
    poll = models.ForeignKey(Poll)
    choice = models.ForeignKey(Choice)

    def __unicode__(self):
        return self.ip

pollsite/polls2/views.py
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.views import generic
from ipware.ip import get_ip

from polls2.models import Poll, Choice, Voter

class IndexView(generic.ListView):
	template_name = 'polls2/index.html'
	context_object_name = 'latest_poll_list'

	def get_queryset(self):
		return Poll.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

	def get_context_data(self, **kwargs):
		context = super(IndexView, self).get_context_data(**kwargs)
		context['trending_polls'] = Poll.objects.order_by('-answers')[:10]
		return context

class DetailView(generic.DetailView):
	model = Poll
	template_name = 'polls2/detail.html'

	def get_object(self, *args, **kwargs):
		return get_object_or_404(Poll, pk=self.kwargs['poll_id'])

class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'polls2/results.html'

    def get_object(self, *args, **kwargs):
        return get_object_or_404(Poll, pk=self.kwargs['poll_id'])

def vote(request, poll_slug, poll_id):
	poll = get_object_or_404(Poll, pk=poll_id)
	try:
		selected_choice = poll.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'polls/detail.html', {
			'poll': poll,
			'error_message': "You did not select a valid choice!"
		})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		poll.answers += 1
		poll.save()
		ip = get_ip(request)
		if ip:
			voter = Voter(ip=ip, choice_id=selected_choice.id, poll_id=poll.id)
			voter.save()

		return HttpResponseRedirect(reverse('polls2:results', args=(poll.slug, poll.id)))

# def index(request):	
# 	context = {}
# 	context['latest_poll_list'] = Poll.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
# 	return render(request, 'polls2/index.html', context)

# def detail(request, poll_slug, poll_id):
# 	try:
# 		poll = Poll.objects.get(pk=poll_id)
# 	except Poll.DoesNotExist:
# 		raise Http404
# 	context = {
# 		'poll': poll,
# 	}
# 	return render(request, 'polls2/detail.html', context)

pollsite/polls2/templates/polls2/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %} {% endblock %} | Pollbin</title>
	<link rel="stylesheet" type="text/css" href="{% static 'polls2/css/fonts.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'polls2/css/style.css' %}" />
</head>
<body>
	<header>
		<div id="logo"><a href="{% url 'polls2:index' %}"><h1>P<span class="emphasis">O</span>LLBIN2</h1>DJANGO DEMO POLLING SITE</a></div>
	</header>
	<div class="container card">
	{% block body_block %}{% endblock %}
	</div>
</body>
</html>

pollsite/polls2/templates/polls2/detail.html
{% extends 'polls2/base.html' %}
{% block title %}{{ poll.question }}{% endblock %}

{% block body_block %}
<div class="detail-card">
	<h3>{{ poll.question }}</h3>
	<ul>
	<form action="{% url 'polls2:vote' poll.slug poll.id %}" method="post">
		{% csrf_token %}
		{% for choice in poll.choice_set.all %}
		<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
		<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
		<br>
		{% endfor %}
		<input type="submit" value="VOTE" />
		{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	</form>
	</ul>
</div>
{% endblock %}

pollsite/polls2/templates/polls2/index.html
{% extends 'polls2/base.html' %}
{% block title %}Welcome to Pollbin!{% endblock %}

{% block body_block %}
<div id="content">
{% if latest_poll_list %}
	<h3><span>LATEST</span></h3>
    <ul>
    {% for poll in latest_poll_list %}
        <li>
        	<a href="{% url 'polls2:detail' poll.slug poll.id %}">{{ poll.question|title }}</a>
        	<span>{{ poll.pub_date|date:"M d Y" }} {{ poll.answers }} hit{{poll.answers|pluralize}}</span>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% if trending_polls %}
	<h3><span>TRENDING</span></h3>
    <ul>
    {% for poll in trending_polls %}
        <li>
	        <a href="{% url 'polls2:detail' poll.slug poll.id %}">{{ poll.question|title }}</a>
	        <span>{{ poll.pub_date|date:"M d Y" }} {{ poll.answers }} hit{{poll.answers|pluralize}}</span>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</div>
{% endblock %}

pollsite/polls2/templates/polls2/results.html
{% extends 'polls2/base.html' %}
{% block title%}{{poll.question}} | Results{% endblock %}

{% block body_block %}
{{poll.question}}
<ul>
{% for choice in poll.choice_set.all %}
	<li>{{ choice.votes }} vote{{ choice.votes|pluralize }} {{ choice.choice_text }}</li>
{% endfor %}
</ul>
{% endblock %}